# Generated by Django 4.1.2 on 2022-10-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('user', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=50)),
                ('linkedIn', models.CharField(max_length=50)),
                ('profile', models.CharField(max_length=50)),
                ('academics_1_institute', models.CharField(max_length=50)),
                ('academics_1_program', models.CharField(max_length=50)),
                ('academics_1_startDate', models.DateField()),
                ('academics_1_endDate', models.DateField()),
                ('academics_1_mark', models.CharField(max_length=50)),
                ('academics_2_institute', models.CharField(max_length=50)),
                ('academics_2_program', models.CharField(max_length=50)),
                ('academics_2_startDate', models.DateField()),
                ('academics_2_endDate', models.DateField()),
                ('academics_2_mark', models.CharField(max_length=50)),
                ('academics_3_institute', models.CharField(max_length=50)),
                ('academics_3_program', models.CharField(max_length=50)),
                ('academics_3_startDate', models.DateField()),
                ('academics_3_endDate', models.DateField()),
                ('academics_3_mark', models.CharField(max_length=50)),
                ('areasOfInterest1', models.CharField(max_length=50)),
                ('areasOfInterest2', models.CharField(max_length=50)),
                ('areasOfInterest3', models.CharField(max_length=50)),
                ('areasOfInterest4', models.CharField(max_length=50)),
                ('paper_1', models.CharField(max_length=50)),
                ('paper_2', models.CharField(max_length=50)),
                ('programmingLanguages', models.CharField(max_length=50)),
                ('tools', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=50)),
                ('project1_title', models.CharField(max_length=50)),
                ('project1_toolUsed', models.CharField(max_length=50)),
                ('project2_title', models.CharField(max_length=50)),
                ('project2_toolUsed', models.CharField(max_length=50)),
                ('project3_title', models.CharField(max_length=50)),
                ('project3_toolUsed', models.CharField(max_length=50)),
                ('project4_title', models.CharField(max_length=50)),
                ('project4_toolUsed', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('achievement1', models.CharField(max_length=50)),
                ('achievement2', models.CharField(max_length=50)),
                ('achievement3', models.CharField(max_length=50)),
                ('achievement4', models.CharField(max_length=50)),
                ('strength1', models.CharField(max_length=50)),
                ('strength2', models.CharField(max_length=50)),
                ('strength3', models.CharField(max_length=50)),
                ('strength4', models.CharField(max_length=50)),
                ('strength5', models.CharField(max_length=50)),
                ('strength6', models.CharField(max_length=50)),
                ('strength7', models.CharField(max_length=50)),
                ('strength8', models.CharField(max_length=50)),
                ('language1', models.CharField(max_length=50)),
                ('language2', models.CharField(max_length=50)),
                ('language3', models.CharField(max_length=50)),
            ],
        ),
    ]
