# Generated by Django 4.1.2 on 2022-10-07 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='image',
        ),
    ]
